### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-images#2]
@johno I updated this module as well, and changed one big thing: previously, full URLs:

```markdown
https://example.com/example.jpg
```

...were linked:

```markdown
[![](https://example.com/example.jpg)](https://example.com/example.jpg)
```

Because that’s what remark does if it sees a full URL.
But paths:

```markdown
/example.jpg
```

...were not linked:

```markdown
![](/example.jpg)
```

I added support for injecting a link around those images:

```markdown
[![](/example.jpg)](/example.jpg)
```

Does that make sense for this plugin?

**Comment by johno** [comment]
Makes sense to me!

**Comment by johno** [comment]
Also added you as an owner 💃

**Comment by wooorm** [comment]
Sweet, thanks, released!
