### ISSUE TITLE
Add option to disable link generation

### ISSUE THREAD

**Issue by enyo** [remarkjs/remark-images#6]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

In my use case I don't want the resulting images to be wrapped in an `<a>` element.

### Solution

Add an additional option field.

### Alternatives

-

**Comment by wooorm** [comment]
Sure, PR welcome

**Comment by wooorm** [comment]
Released in [`4.1.0`](https://github.com/remarkjs/remark-images/releases/tag/4.1.0)!
